// Generated by `supabase gen types typescript` (via the Supabase connector).
// Do not edit by hand — regenerate when the schema changes.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      exercises: {
        Row: {
          created_at: string
          id: string
          muscle_group: string | null
          name: string
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          muscle_group?: string | null
          name: string
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          muscle_group?: string | null
          name?: string
          user_id?: string
        }
        Relationships: []
      }
      feedback: {
        Row: {
          body: string
          created_at: string
          id: string
          status: Database["public"]["Enums"]["feedback_status"]
          user_id: string
        }
        Insert: {
          body: string
          created_at?: string
          id?: string
          status?: Database["public"]["Enums"]["feedback_status"]
          user_id: string
        }
        Update: {
          body?: string
          created_at?: string
          id?: string
          status?: Database["public"]["Enums"]["feedback_status"]
          user_id?: string
        }
        Relationships: []
      }
      habit_logs: {
        Row: {
          count: number
          created_at: string
          date: string
          habit_id: string
          id: string
          note: string | null
          user_id: string
        }
        Insert: {
          count?: number
          created_at?: string
          date: string
          habit_id: string
          id?: string
          note?: string | null
          user_id: string
        }
        Update: {
          count?: number
          created_at?: string
          date?: string
          habit_id?: string
          id?: string
          note?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "habit_logs_habit_id_fkey"
            columns: ["habit_id"]
            isOneToOne: false
            referencedRelation: "habits"
            referencedColumns: ["id"]
          },
        ]
      }
      habits: {
        Row: {
          archived_at: string | null
          color: string | null
          created_at: string
          description: string | null
          frequency: Database["public"]["Enums"]["habit_frequency"]
          icon: string | null
          id: string
          name: string
          sort_order: number
          target_count: number
          time_of_day: Database["public"]["Enums"]["habit_time_of_day"]
          user_id: string
        }
        Insert: {
          archived_at?: string | null
          color?: string | null
          created_at?: string
          description?: string | null
          frequency?: Database["public"]["Enums"]["habit_frequency"]
          icon?: string | null
          id?: string
          name: string
          sort_order?: number
          target_count?: number
          time_of_day?: Database["public"]["Enums"]["habit_time_of_day"]
          user_id: string
        }
        Update: {
          archived_at?: string | null
          color?: string | null
          created_at?: string
          description?: string | null
          frequency?: Database["public"]["Enums"]["habit_frequency"]
          icon?: string | null
          id?: string
          name?: string
          sort_order?: number
          target_count?: number
          time_of_day?: Database["public"]["Enums"]["habit_time_of_day"]
          user_id?: string
        }
        Relationships: []
      }
      profiles: {
        Row: {
          avatar_url: string | null
          created_at: string
          display_name: string | null
          id: string
          role: Database["public"]["Enums"]["user_role"]
          timezone: string
        }
        Insert: {
          avatar_url?: string | null
          created_at?: string
          display_name?: string | null
          id: string
          role?: Database["public"]["Enums"]["user_role"]
          timezone?: string
        }
        Update: {
          avatar_url?: string | null
          created_at?: string
          display_name?: string | null
          id?: string
          role?: Database["public"]["Enums"]["user_role"]
          timezone?: string
        }
        Relationships: []
      }
      quotes: {
        Row: {
          author: string | null
          id: string
          text: string
        }
        Insert: {
          author?: string | null
          id?: string
          text: string
        }
        Update: {
          author?: string | null
          id?: string
          text?: string
        }
        Relationships: []
      }
      reflections: {
        Row: {
          body: string
          created_at: string
          date: string
          id: string
          quote_id: string | null
          user_id: string
        }
        Insert: {
          body: string
          created_at?: string
          date: string
          id?: string
          quote_id?: string | null
          user_id: string
        }
        Update: {
          body?: string
          created_at?: string
          date?: string
          id?: string
          quote_id?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "reflections_quote_id_fkey"
            columns: ["quote_id"]
            isOneToOne: false
            referencedRelation: "quotes"
            referencedColumns: ["id"]
          },
        ]
      }
      set_logs: {
        Row: {
          done: boolean
          id: string
          logged_at: string | null
          reps: number | null
          set_number: number
          weight: number | null
          workout_exercise_id: string
        }
        Insert: {
          done?: boolean
          id?: string
          logged_at?: string | null
          reps?: number | null
          set_number: number
          weight?: number | null
          workout_exercise_id: string
        }
        Update: {
          done?: boolean
          id?: string
          logged_at?: string | null
          reps?: number | null
          set_number?: number
          weight?: number | null
          workout_exercise_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "set_logs_workout_exercise_id_fkey"
            columns: ["workout_exercise_id"]
            isOneToOne: false
            referencedRelation: "workout_exercises"
            referencedColumns: ["id"]
          },
        ]
      }
      workout_exercises: {
        Row: {
          exercise_id: string
          id: string
          sort_order: number
          target_reps: number | null
          target_sets: number | null
          target_weight: number | null
          workout_id: string
        }
        Insert: {
          exercise_id: string
          id?: string
          sort_order?: number
          target_reps?: number | null
          target_sets?: number | null
          target_weight?: number | null
          workout_id: string
        }
        Update: {
          exercise_id?: string
          id?: string
          sort_order?: number
          target_reps?: number | null
          target_sets?: number | null
          target_weight?: number | null
          workout_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "workout_exercises_exercise_id_fkey"
            columns: ["exercise_id"]
            isOneToOne: false
            referencedRelation: "exercises"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "workout_exercises_workout_id_fkey"
            columns: ["workout_id"]
            isOneToOne: false
            referencedRelation: "workouts"
            referencedColumns: ["id"]
          },
        ]
      }
      workouts: {
        Row: {
          completed_at: string | null
          created_at: string
          id: string
          name: string
          recurrence: Database["public"]["Enums"]["workout_recurrence"]
          recurrence_days: number[] | null
          recurrence_interval: number | null
          scheduled_date: string | null
          user_id: string
        }
        Insert: {
          completed_at?: string | null
          created_at?: string
          id?: string
          name: string
          recurrence?: Database["public"]["Enums"]["workout_recurrence"]
          recurrence_days?: number[] | null
          recurrence_interval?: number | null
          scheduled_date?: string | null
          user_id: string
        }
        Update: {
          completed_at?: string | null
          created_at?: string
          id?: string
          name?: string
          recurrence?: Database["public"]["Enums"]["workout_recurrence"]
          recurrence_days?: number[] | null
          recurrence_interval?: number | null
          scheduled_date?: string | null
          user_id?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      is_admin: { Args: never; Returns: boolean }
      is_owner: { Args: never; Returns: boolean }
      admin_delete_user: { Args: { target: string }; Returns: undefined }
      set_user_role: {
        Args: { target: string; new_role: Database["public"]["Enums"]["user_role"] }
        Returns: undefined
      }
      landing_stats: {
        Args: never
        Returns: {
          members: number
          longest_streak: number
          avg_completion: number
        }[]
      }
    }
    Enums: {
      feedback_status: "open" | "planned" | "done" | "closed"
      habit_frequency:
        | "daily"
        | "weekly"
        | "x_per_week"
        | "every_n_days"
        | "weekdays"
        | "every_n_weeks"
      habit_time_of_day: "anytime" | "morning" | "afternoon" | "evening"
      user_role: "user" | "admin" | "owner"
      workout_recurrence: "none" | "daily" | "weekdays" | "every_n_days"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      feedback_status: ["open", "planned", "done", "closed"],
      habit_frequency: [
        "daily",
        "weekly",
        "x_per_week",
        "every_n_days",
        "weekdays",
        "every_n_weeks",
      ],
      habit_time_of_day: ["anytime", "morning", "afternoon", "evening"],
      user_role: ["user", "admin", "owner"],
      workout_recurrence: ["none", "daily", "weekdays", "every_n_days"],
    },
  },
} as const
